# Generated by Django 6.0.5 on 2026-05-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamento', '0001_initial'),
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(max_length=100, verbose_name='Frequência (Ex: 8h em 8h)')),
                ('duracao_dias', models.PositiveIntegerField(verbose_name='Duração (Dias)')),
                ('dose', models.CharField(max_length=50, verbose_name='Dose (Ex: 1 comprimido)')),
                ('concentracao', models.CharField(max_length=50, verbose_name='Concentração (Ex: 500mg)')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes_receitas', to='medicamento.medicamento', verbose_name='Medicamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_medicamentos', to='receita.receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Medicamento da Receita',
                'verbose_name_plural': 'Medicamentos da Receita',
                'unique_together': {('receita', 'medicamento')},
            },
        ),
    ]
