# Generated by Django 6.0.5 on 2026-05-25 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examesolicitado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resultado', models.DateField()),
                ('conclusoes', models.TextField()),
                ('valor', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=50)),
                ('exame_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examesolicitado.examesolicitado')),
            ],
        ),
    ]
