# Generated by Django 6.0.5 on 2026-05-25 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '__first__'),
        ('paciente', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateTimeField(verbose_name='Data e Hora Agendada')),
                ('status', models.CharField(choices=[('AG', 'Agendada'), ('RE', 'Realizada'), ('CA', 'Cancelada')], default='AG', max_length=2)),
                ('motivo', models.TextField(verbose_name='Motivo da Consulta')),
                ('nivel_prioridade', models.CharField(choices=[('B', 'Baixa'), ('N', 'Normal'), ('A', 'Alta'), ('U', 'Urgência')], default='N', max_length=1)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medico.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='paciente.paciente')),
            ],
        ),
    ]
