# Generated by Django 6.0.5 on 2026-05-25 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exame', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preparo', models.TextField()),
                ('exige_jejum', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
            ],
            options={
                'verbose_name': 'Exame solicitado',
                'verbose_name_plural': 'Exames solicitados',
                'ordering': ['id'],
            },
        ),
    ]
