# Generated by Django 6.0.5 on 2026-05-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('instrucoes', models.TextField(blank=True, null=True, verbose_name='Instruções Gerais')),
                ('e_digital', models.BooleanField(default=True, verbose_name='É Digital?')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='consulta.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
