# Generated by Django 6.0.5 on 2026-05-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamento', '0001_initial'),
        ('receita', '0001_initial'),
        ('receitaMedicamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='medicamentos',
            field=models.ManyToManyField(related_name='receitas', through='receitaMedicamento.ReceitaMedicamento', to='medicamento.medicamento', verbose_name='Medicamentos'),
        ),
    ]
