# Generated by Django 6.0.5 on 2026-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_referencia', models.CharField(max_length=200)),
                ('principio_ativo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=150)),
                ('e_controlado', models.BooleanField(default=False)),
                ('tem_generico', models.BooleanField(default=True)),
            ],
        ),
    ]
