# Generated by Django 6.0.5 on 2026-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cid', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('sintomas', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('status_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['id'],
            },
        ),
    ]
