# Generated by Django 6.0.5 on 2026-05-25 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cid', '0001_initial'),
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_autenticacao', models.CharField(max_length=50, unique=True)),
                ('data_inicio_afastamento', models.DateField()),
                ('quantidade_dias', models.IntegerField()),
                ('tipo_atestado', models.CharField(choices=[('MEDICO', 'Médico'), ('ODONTO', 'Odontológico'), ('OUTRO', 'Outro')], max_length=40, verbose_name='Tipo de Atestado')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cid.cid')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
            ],
        ),
    ]
